// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('src/helper/helper.js', ['datalayerhelper.helper.DataLayerHelper'], ['datalayerhelper.helper.utils', 'datalayerhelper.plain'], {'module': 'goog'});
