// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('src/helper/helper.js', ['data_layer_helper.helper.DataLayerHelper'], ['data_layer_helper.helper.utils', 'data_layer_helper.logging', 'data_layer_helper.plain'], {'module': 'goog'});
